#config_version=6

####################################################################################
# SHOT MADE CALLOUT RANDOMIZER MODE
####################################################################################
# Centralized random voice callout system for mode shot hits.
# 
# Priority: 150 (above base 100, below mission modes 600)
# Runs: From ball_starting until ball_ending
#
# USAGE FROM ANY MODE:
#   Just post the event "play_shot_made_callout" and this mode will
#   randomly select and play one of the voice callout sounds.
#
#   Example in your mode's event_player:
#     event_player:
#       some_mode_shot_hit:
#         - play_shot_made_callout
#
# SOUND FILES: sounds/voice/shot_made/
#   voice_beautiful_shot.mp3
#   voice_bullseye.mp3
#   voice_clean_hit.mp3
#   voice_direct_hit.mp3
#   voice_good_hit.mp3
#   voice_nice_shot.mp3
#   voice_perfect.mp3
#   voice_right_on_target.mp3
#   voice_smooth.mp3
#   voice_solid_flying.mp3
#   voice_thats_a_great_shot.mp3
#   voice_thats_how_its_done.mp3
#   voice_too_easy.mp3
#   voice_you_nailed_it.mp3
#   voice_youre_a_hell_of_a_pilot.mp3
####################################################################################

mode:
  start_events: ball_starting
  stop_events: ball_ending
  priority: 150
  game_mode: true

####################################################################################
# RANDOM EVENT PLAYER
####################################################################################
# When any mode posts "play_shot_made_callout", this picks one at random.
# force_different: true prevents the same callout playing twice in a row.
####################################################################################

random_event_player:
  play_shot_made_callout:
    force_different: true
    events:
      - play_voice_beautiful_shot
      - play_voice_bullseye
      - play_voice_clean_hit
      - play_voice_direct_hit
      - play_voice_good_hit
      - play_voice_nice_shot
      - play_voice_perfect
      - play_voice_right_on_target
      - play_voice_smooth
      - play_voice_solid_flying
      - play_voice_thats_a_great_shot
      - play_voice_thats_how_its_done
      - play_voice_too_easy
      - play_voice_you_nailed_it
      - play_voice_youre_a_hell_of_a_pilot

####################################################################################
# SOUND PLAYER
####################################################################################
# Each random event triggers its corresponding voice sound on the voice bus.
####################################################################################

sound_player:
  play_voice_beautiful_shot:
    voice_beautiful_shot:
      bus: voice
      loops: 0

  play_voice_bullseye:
    voice_bullseye:
      bus: voice
      loops: 0

  play_voice_clean_hit:
    voice_clean_hit:
      bus: voice
      loops: 0

  play_voice_direct_hit:
    voice_direct_hit:
      bus: voice
      loops: 0

  play_voice_good_hit:
    voice_good_hit:
      bus: voice
      loops: 0

  play_voice_nice_shot:
    voice_nice_shot:
      bus: voice
      loops: 0

  play_voice_perfect:
    voice_perfect:
      bus: voice
      loops: 0

  play_voice_right_on_target:
    voice_right_on_target:
      bus: voice
      loops: 0

  play_voice_smooth:
    voice_smooth:
      bus: voice
      loops: 0

  play_voice_solid_flying:
    voice_solid_flying:
      bus: voice
      loops: 0

  play_voice_thats_a_great_shot:
    voice_thats_a_great_shot:
      bus: voice
      loops: 0

  play_voice_thats_how_its_done:
    voice_thats_how_its_done:
      bus: voice
      loops: 0

  play_voice_too_easy:
    voice_too_easy:
      bus: voice
      loops: 0

  play_voice_you_nailed_it:
    voice_you_nailed_it:
      bus: voice
      loops: 0

  play_voice_youre_a_hell_of_a_pilot:
    voice_youre_a_hell_of_a_pilot:
      bus: voice
      loops: 0