#config_version=6

####################################################################################
# SHOT MISSED CALLOUT RANDOMIZER MODE
####################################################################################
# Centralized random voice callout system for mode shot misses / bad shots.
# 
# Priority: 150 (above base 100, below mission modes 600)
# Runs: From ball_starting until ball_ending
#
# USAGE FROM ANY MODE:
#   Just post the event "play_shot_missed_callout" and this mode will
#   randomly select and play one of the voice callout sounds.
#
#   Example in your mode's event_player:
#     event_player:
#       some_mode_bad_shot:
#         - play_shot_missed_callout
#
# SOUND FILES: sounds/voice/shot_missed/
#   voice_bad_move.mp3
#   voice_get_back_in_formation.mp3
#   voice_negative.mp3
#   voice_not_good.mp3
#   voice_off_target.mp3
#   voice_stay_with_me.mp3
#   voice_thats_not_it.mp3
#   voice_watch_your_six.mp3
#   voice_wrong_way.mp3
#   voice_you_lost_it.mp3
#   voice_youre_off_course.mp3
#   voice_pull_it_together.mp3
#   voice_come_on_mav.mp3
#   voice_focus.mp3
#   voice_stay_on_target.mp3
####################################################################################

mode:
  start_events: ball_starting
  stop_events: ball_ending
  priority: 150
  game_mode: true

####################################################################################
# RANDOM EVENT PLAYER
####################################################################################
# When any mode posts "play_shot_missed_callout", this picks one at random.
# force_different: true prevents the same callout playing twice in a row.
####################################################################################

random_event_player:
  play_shot_missed_callout:
    force_different: true
    events:
      - play_voice_bad_move
      - play_voice_get_back_in_formation
      - play_voice_negative
      - play_voice_not_good
      - play_voice_off_target
      - play_voice_stay_with_me
      - play_voice_thats_not_it
      - play_voice_watch_your_six
      - play_voice_wrong_way
      - play_voice_you_lost_it
      - play_voice_youre_off_course
      - play_voice_pull_it_together
      - play_voice_come_on_mav
      - play_voice_focus
      - play_voice_stay_on_target

####################################################################################
# SOUND PLAYER
####################################################################################
# Each random event triggers its corresponding voice sound on the voice bus.
####################################################################################

sound_player:
  play_voice_bad_move:
    voice_bad_move:
      bus: voice
      loops: 0

  play_voice_get_back_in_formation:
    voice_get_back_in_formation:
      bus: voice
      loops: 0

  play_voice_negative:
    voice_negative:
      bus: voice
      loops: 0

  play_voice_not_good:
    voice_not_good:
      bus: voice
      loops: 0

  play_voice_off_target:
    voice_off_target:
      bus: voice
      loops: 0

  play_voice_stay_with_me:
    voice_stay_with_me:
      bus: voice
      loops: 0

  play_voice_thats_not_it:
    voice_thats_not_it:
      bus: voice
      loops: 0

  play_voice_watch_your_six:
    voice_watch_your_six:
      bus: voice
      loops: 0

  play_voice_wrong_way:
    voice_wrong_way:
      bus: voice
      loops: 0

  play_voice_you_lost_it:
    voice_you_lost_it:
      bus: voice
      loops: 0

  play_voice_youre_off_course:
    voice_youre_off_course:
      bus: voice
      loops: 0

  play_voice_pull_it_together:
    voice_pull_it_together:
      bus: voice
      loops: 0

  play_voice_come_on_mav:
    voice_come_on_mav:
      bus: voice
      loops: 0

  play_voice_focus:
    voice_focus:
      bus: voice
      loops: 0

  play_voice_stay_on_target:
    voice_stay_on_target:
      bus: voice
      loops: 0