#config_version=6

mode:
  start_events: start_mode_bumpers
  stop_events: stop_mode_bumpers
  priority: 200

shots:
   bumper_left:
     switch: s_bumper_left
   bumper_center:
     switch: s_bumper_center
   bumper_right:
     switch: s_bumper_right

shot_groups:
  bumpers:
    shots: bumper_left, bumper_center, bumper_right

variable_player:
  bumpers_hit:
    score:
      action: add
      int: 1000 * current_player.total_scoring_multiplier