#config_version=6

# NOTE: All lights set to type: rgb (Red-Green-Blue) - standard color order
# The fade bug fix (fade: 0ms in mode files) resolves the LED crash issue

lights:

#Insert Lights (Channel 0-63)

#Eject/Shoot Again
  l_eject:
    number: light_expansion_board-1-21
    subtype: led
    type: rgb
    tags: inserts, eject, light_eject
  l_shoot_again:
    number: light_expansion_board-1-22
    subtype: led
    type: rgb
    tags: inserts, shoot_again, light_shoot_again

#Inlane/Outlane Lights
  l_goose_g:
    number: light_expansion_board-1-20
    subtype: led
    type: rgb
    tags: inserts, goose, light_goose_g
  l_goose_o_left:
    number: light_expansion_board-1-19
    subtype: led
    type: rgb
    tags: inserts, goose, light_goose_o_left
  l_goose_o_right:
    number: light_expansion_board-1-1
    subtype: led
    type: rgb
    tags: inserts, goose, light_goose_o_right
  l_goose_s:
    number: light_expansion_board-1-2
    subtype: led
    type: rgb
    tags: inserts, goose, light_goose_s
  l_goose_e:
    number: light_expansion_board-1-3
    subtype: led
    type: rgb
    tags: inserts, goose, light_goose_e
  l_mig_m:
    number: light_expansion_board-2-11
    subtype: led
    type: rgb
    tags: inserts, mig_light, mig_m
  l_mig_i:
    number: light_expansion_board-2-12
    subtype: led
    type: rgb
    tags: inserts, mig_light, mig_i
  l_mig_g:
    number: light_expansion_board-2-13
    subtype: led
    type: rgb
    tags: inserts, mig_light, mig_g

#Iceman Lights
  l_iceman_i:
    number: light_expansion_board-2-1
    subtype: led
    type: rgb
    tags: inserts, iceman, light_iceman_i
  l_iceman_c:
    number: light_expansion_board-2-2
    subtype: led
    type: rgb
    tags: inserts, iceman, light_iceman_c
  l_iceman_e:
    number: light_expansion_board-2-3
    subtype: led
    type: rgb
    tags: inserts, iceman, light_iceman_e
  l_iceman_m:
    number: light_expansion_board-1-6
    subtype: led
    type: rgb
    tags: inserts, iceman, light_iceman_m
  l_iceman_a:
    number: light_expansion_board-1-5
    subtype: led
    type: rgb
    tags: inserts, iceman, light_iceman_a
  l_iceman_n:
    number: light_expansion_board-1-4
    subtype: led
    type: rgb
    tags: inserts, iceman, light_iceman_n

#Lock Lights
  l_lock_l:
    number: light_expansion_board-2-7
    subtype: led
    type: rgb
    tags: inserts, lock, light_lock_l
  l_lock_o:
    number: light_expansion_board-2-8
    subtype: led
    type: rgb
    tags: inserts, lock, light_lock_o
  l_lock_c:
    number: light_expansion_board-2-15
    subtype: led
    type: rgb
    tags: inserts, lock, light_lock_c
  l_lock_k:
    number: light_expansion_board-2-21
    subtype: led
    type: rgb
    tags: inserts, lock, light_lock_k
  l_lock_lit:
    number: light_expansion_board-2-17
    subtype: led
    type: rgb
    tags: inserts, lock, light_lock_lit

# Mode Lights

  l_mode_rescue_cougar:
    number: light_expansion_board-1-11
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_rescue_cougar
  l_mode_balls_of_fire:
    number: light_expansion_board-1-10
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_great_balls_of_fire
  l_mode_cool_under_pressure:
    number: light_expansion_board-1-9
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_cool_under_pressure
  l_mode_battle_jester:
    number: light_expansion_board-1-8
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_battle_jester
  l_mode_no_points_for_second_place:
    number: light_expansion_board-1-7
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_no_points_for_second_place
  l_mode_edge_of_space:
    number: light_expansion_board-1-18
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_edge_of_space
  l_mode_below_the_hard_deck:
    number: light_expansion_board-1-17
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_below_the_hard_deck
  l_mode_canyon_run:
    number: light_expansion_board-1-16
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_canyon_run
  l_mode_rise_of_phoenix:
    number: light_expansion_board-1-15
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_rise_of_phoenix
  l_mode_no_margin_for_error:
    number: light_expansion_board-1-14
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_no_margin_for_error
  l_mode_inverted:
    number: light_expansion_board-1-25
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_inverted
  l_mode_missles:
    number: light_expansion_board-1-24
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_missles
  l_mode_afterburner:
    number: light_expansion_board-1-23
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_afterburner
  l_mode_wingman:
    number: light_expansion_board-1-26
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_wingman
  l_mode_dogfight:
    number: light_expansion_board-1-27
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_dogfight
  l_mode_top_top_gun:
    number: light_expansion_board-1-12
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_top_top_gun
  l_mode_gun_top_gun:
    number: light_expansion_board-1-13
    subtype: led
    type: rgb
    tags: inserts, pilot_mission, light_gun_top_gun

#Shot Lights

  l_shot_left_lane:
    number: light_expansion_board-2-4
    subtype: led
    type: rgb
    tags: inserts, shot, light_left_lane
  l_shot_left_orbit:
    number: light_expansion_board-2-6
    subtype: led
    type: rgb
    tags: inserts, shot, light_left_orbit
  l_shot_left_ramp:
    number: light_expansion_board-2-5
    subtype: led
    type: rgb
    tags: inserts, shot, light_left_ramp
  l_shot_spinner:
    number: light_expansion_board-2-10
    subtype: led
    type: rgb
    tags: inserts, shot, light_spinner
  l_shot_barrier:
    number: light_expansion_board-2-9
    subtype: led
    type: rgb
    tags: inserts, shot, light_barrier
  l_shot_tower_ramp:
    number: light_expansion_board-2-14
    subtype: led
    type: rgb
    tags: inserts, shot, light_tower_ramp
  l_shot_upper_orbit:
    number: light_expansion_board-2-16
    subtype: led
    type: rgb
    tags: inserts, shot, light_upper_orbit
  l_shot_middle_ramp:
    number: light_expansion_board-2-18
    subtype: led
    type: rgb
    tags: inserts, shot, light_middle_ramp
  l_shot_right_orbit:
    number: light_expansion_board-2-20
    subtype: led
    type: rgb
    tags: inserts, shot, light_right_orbit
  l_shot_pilot_gear:
    number: light_expansion_board-2-19
    subtype: led
    type: rgb
    tags: inserts, lock, light_pilot_gear

#GI Lights (Channel 64-127)
  l_gi_light_1:
    number: light_expansion_board-4-1           
    subtype: led
    type: rgb
    label: "Right Return Lane GI Left"
    tags: gi_lights, right_return_lane_gi_left
  l_gi_light_2:
    number: light_expansion_board-4-2
    subtype: led
    type: rgb
    label: "Right Return Lane GI Right"
    tags: gi_lights, right_return_lane_gi_right
  l_gi_light_3:
    number: light_expansion_board-4-3
    subtype: led
    type: rgb
    label: "Left Return Lane GI Left"
    tags: gi_lights, left_return_lane_gi_left
  l_gi_light_4:
    number: light_expansion_board-4-4
    subtype: led
    type: rgb
    label: "Left Return Lane GI Right"
    tags: gi_lights, left_return_lane_gi_right
  l_gi_light_5:
    number: light_expansion_board-4-5
    subtype: led
    type: rgb
    label: "Left Sling GI 1"
    tags: gi_lights, left_sling_gi_1
  l_gi_light_6:
    number: light_expansion_board-4-6
    subtype: led
    type: rgb
    label: "Left Sling GI 2"
    tags: gi_lights, left_sling_gi_2
  l_gi_light_7:
    number: light_expansion_board-4-7
    subtype: led
    type: rgb
    label: "Right Sling GI 1"
    tags: gi_lights, right_sling_gi_1
  l_gi_light_8:
    number: light_expansion_board-4-8
    subtype: led
    type: rgb
    label: "Right Sling GI 2"
    tags: gi_lights, right_sling_gi_2
  l_gi_light_9:
    number: light_expansion_board-4-9
    subtype: led
    type: rgb
    label: "Left Outlane GI"
    tags: gi_lights, left_outlane_gi
  l_gi_light_10:
    number: light_expansion_board-4-10
    subtype: led
    type: rgb
    label: "Right Outlane GI"
    tags: gi_lights, right_outlane_gi
  l_gi_light_11:
    number: light_expansion_board-4-11
    subtype: led
    type: rgb
    label: "Pop Area GI 1"
    tags: gi_lights, pop_area_gi_lower
  l_gi_light_12:
    number: light_expansion_board-4-12
    subtype: led
    type: rgb
    label: "Pop Area GI 2"
    tags: gi_lights, pop_area_gi_right
  l_gi_light_13:
    number: light_expansion_board-4-13
    subtype: led
    type: rgb
    label: "Left MIG Lane GI"
    tags: gi_lights, mig_gi_left
  l_gi_light_14:
    number: light_expansion_board-4-14
    subtype: led
    type: rgb
    label: "Middle MIG Lane GI"
    tags: gi_lights, mig_gi_middle
  l_gi_light_15:
    number: light_expansion_board-4-15
    subtype: led
    type: rgb
    label: "Right MIG Lane GI"
    tags: gi_lights, mig_gi_right
  l_gi_light_16:
    number: light_expansion_board-4-16
    subtype: led
    type: rgb
    label: "Left Orbit GI"
    tags: gi_lights, left_orbit_gi
  l_gi_light_17:
    number: light_expansion_board-4-17
    subtype: led
    type: rgb
    label: "Right Orbit GI 1"
    tags: gi_lights, right_orbit_gi_upper
  l_gi_light_18:
    number: light_expansion_board-4-18
    subtype: led
    type: rgb
    label: "Right Orbit GI 2"
    tags: gi_lights, right_orbit_gi_right
  l_gi_light_19:
    number: light_expansion_board-4-19
    subtype: led
    type: rgb
    label: "Middle Orbit GI"
    tags: gi_lights, middle_orbit_gi
  l_gi_light_20:
    number: light_expansion_board-4-20
    subtype: led
    type: rgb
    label: "Back Board GI 1"
    tags: above_playfield_lights, gi_lights
  l_gi_light_21:
    number: light_expansion_board-4-21
    subtype: led
    type: rgb
    label: "Back Board GI 2"
    tags: above_playfield_lights, gi_lights


#Pop Bumper Lights (Channel TBD)
  l_gi_light_pop_left:
    number: light_expansion_board-3-1           
    subtype: led
    type: rgb
    label: "Left Pop Bumper"
    tags: left_pop_bumper
  l_gi_light_pop_right:
    number: light_expansion_board-3-2
    subtype: led
    type: rgb
    label: "Right Pop Bumper"
    tags: right_pop_bumper
  l_gi_light_pop_bottom:
    number: light_expansion_board-3-3
    subtype: led
    type: rgb
    label: "Bottom Pop Bumper"
    tags: bottom_pop_bumper


#Above Playfield Lights (Channel 128-191)


  l_gi_light_22:
    number: light_expansion_board-3-4
    subtype: led
    type: rgb
    label: "Back Board GI 1"
    tags: above_playfield_lights, gi_lights
  l_gi_light_23:
    number: light_expansion_board-3-5
    subtype: led
    type: rgb
    label: "Back Board GI 2"
    tags: above_playfield_lights, gi_lights
  l_gi_light_24:
    number: light_expansion_board-3-6
    subtype: led
    type: rgb
    label: "Back Board GI 3"
    tags: above_playfield_lights, gi_lights
  l_gi_light_25:
    number: light_expansion_board-3-7
    subtype: led
    type: rgb
    label: "Back Board GI 4"
    tags: above_playfield_lights, gi_lights
  l_gi_light_26:
    number: light_expansion_board-3-8
    subtype: led
    type: rgb
    label: "Back Board GI 5"
    tags: above_playfield_lights, gi_lights
  l_gi_light_27:
    number: light_expansion_board-3-9
    subtype: led
    type: rgb
    label: "Back Board GI 6"
    tags: above_playfield_lights, gi_lights
  l_apron_light_1:
    number: light_expansion_board-3-19
    subtype: led
    type: rgb
    label: "apron GI 1"
    tags: above_playfield_lights, gi_lights
  l_apron_light_2:
    number: light_expansion_board-3-20
    subtype: led
    type: rgb
    label: "apron GI 2"
    tags: above_playfield_lights, gi_lights
  l_lock_mav:
    number: light_expansion_board-3-11
    subtype: led
    type: rgb
    tags: above_playfield_lights, lock, light_lock_mav
  l_lock_goose:
    number: light_expansion_board-3-10
    subtype: led
    type: rgb
    tags: above_playfield_lights, lock, light_lock_goose
  l_pilot_mission_lit:
    number: light_expansion_board-3-12
    subtype: led
    type: rgb
    tags: above_playfield_lights, pilot_mission_indicator, light_pilot_mission_lit
  l_pilot_training_lit:
    number: light_expansion_board-3-16
    subtype: led
    type: rgb
    tags: above_playfield_lights, pilot_training_indicator, light_pilot_training_lit
  l_multiball_lit:
    number: light_expansion_board-3-14
    subtype: led
    type: rgb
    tags: above_playfield_lights, light_multiball_lit
  l_final_battle_lit:
    number: light_expansion_board-3-15
    subtype: led
    type: rgb
    tags: above_playfield_lights, final_battle_lit
  l_extra_ball_lit:
    number: light_expansion_board-3-18
    subtype: led
    type: rgb
    tags: above_playfield_lights, extra_ball_lit
  l_hard_deck_lit:
    number: light_expansion_board-3-17
    subtype: led
    type: rgb
    tags: above_playfield_lights, hard_deck_lit
  l_mystery_lit:
    number: light_expansion_board-3-13
    subtype: led
    type: rgb
    tags: above_playfield_lights, mystery_lit