#config_version=6

##############################################################################
# REVERSED FLIPPERS CONFIGURATION
# Used by pilot_training_mission_inverted mode
#
# Normal mapping:
#   s_flipper_left → c_flipper_left, c_flipper_left_upper
#   s_flipper_right → c_flipper_right
#
# Reversed mapping (this file):
#   s_flipper_left → c_flipper_right
#   s_flipper_right → c_flipper_left, c_flipper_left_upper
#
# ADD THIS FILE TO config.yaml:
#   config:
#     - config_reversed_flippers.yaml
##############################################################################

flippers:
  ##############################################################################
  # REVERSED LEFT FLIPPER
  # Activated by RIGHT flipper button (s_flipper_right)
  ##############################################################################
  reversed_left_flipper:
    main_coil: c_flipper_left
    activation_switch: s_flipper_right
    eos_switch: s_flipper_left_eos
    label: reversed_left_flipper
    enable_events: enable_reversed_flippers
    disable_events: disable_reversed_flippers, ball_will_end

  ##############################################################################
  # REVERSED LEFT UPPER FLIPPER
  # Activated by RIGHT flipper button (s_flipper_right)
  ##############################################################################
  reversed_left_upper_flipper:
    main_coil: c_flipper_left_upper
    activation_switch: s_flipper_right
    eos_switch: s_flipper_left_upper_eos
    label: reversed_left_upper_flipper
    enable_events: enable_reversed_flippers
    disable_events: disable_reversed_flippers, ball_will_end

  ##############################################################################
  # REVERSED RIGHT FLIPPER
  # Activated by LEFT flipper button (s_flipper_left)
  ##############################################################################
  reversed_right_flipper:
    main_coil: c_flipper_right
    activation_switch: s_flipper_left
    eos_switch: s_flipper_right_eos
    label: reversed_right_flipper
    enable_events: enable_reversed_flippers
    disable_events: disable_reversed_flippers, ball_will_end