#config_version=6

##############################################################################
# FLIPPER CONFIGURATION - Top Gun Pinball
# 
# Normal flippers are enabled by default during gameplay.
# For reversed flipper modes (like pilot_training_mission_inverted),
# these can be disabled via disable_normal_flippers event and 
# reversed_flippers enabled via enable_reversed_flippers event.
##############################################################################

flippers:
  left_flipper:
    main_coil: c_flipper_left
    activation_switch: s_flipper_left
    eos_switch: s_flipper_left_eos
    label: left_flipper
    enable_events: ball_started, enable_normal_flippers
    disable_events: ball_will_end, disable_normal_flippers

  left_upper_flipper:
    main_coil: c_flipper_left_upper
    activation_switch: s_flipper_left_upper
    eos_switch: s_flipper_left_upper_eos
    label: left_upper_flipper
    enable_events: ball_started, enable_normal_flippers
    disable_events: ball_will_end, disable_normal_flippers

  right_flipper:
    main_coil: c_flipper_right
    activation_switch: s_flipper_right
    eos_switch: s_flipper_right_eos
    label: right_flipper
    enable_events: ball_started, enable_normal_flippers
    disable_events: ball_will_end, disable_normal_flippers