#config_version=6

# Number Format: I/O board name then number on the board.  EX: playfield_board_lower-3
# Label: What will show up in service mode
# Switches Available
  # Cabinet Board -
    # Coin Door Slot - 1
    # J1 Slot - 14,15
    # J10 - 16,17,18,19,20,21,22,23
    # J11 - (Bill/Cards/Ticket) All Open
  # Playfield Board Lower
    # J3 - All Used
    # J6 - 19,20,21,22,23
    # J8 - All Open
    # J9 - All Open
  # Playfield Board Upper
    # J3 - 14
    # J6 - 23
    # J8 - 7
    # J9 - 24,28,29,30,31

switches:

  # Cabinet Switches - J1 (#14,15 available) (all wired)
  s_start:
    number: cabinet_board-8
    label: "Start Button"
    tags: start
  s_tilt:
    number: cabinet_board-13
    label: "Tilt"
    tags: tilt_warning

  # Coin Door Switches - Coin Door (#1 available) (all Wired)
  s_coin_door:
    number: cabinet_board-0
    label: "Coin Door Switch"
    type: NC
    tags: service_door_open, 48v_power_off
  s_coin_door_service_1:
    number: cabinet_board-7
    label: "Service Escape Button"
    tags: service_esc
  s_coin_door_service_2:
    number: cabinet_board-6
    label: "Service Down Button"
    tags: service_down
  s_coin_door_service_3:
    number: cabinet_board-5
    label: "Service Up Button"
    tags: service_up
  s_coin_door_service_4:
    number: cabinet_board-4
    label: "Service Enter Button"
    tags: service_enter
  s_coin_door_credit_right:
    number: cabinet_board-3
    label: "Coin Door Credit Right"
    tags: credit_right
  s_coin_door_credit_left:
    number: cabinet_board-2
    label: "Coin Door Credit Left"
    tags: credit_left

  # Flippers
  s_flipper_left:
    number: cabinet_board-10 
    debounce: quick
    label: "Left Flipper Switch"
    tags: left_flipper
  s_flipper_left_eos:
    number: playfield_board_lower-8
    label: "Left Flipper EOS"
    type: NC
  s_flipper_left_upper:
    number: cabinet_board-11
    debounce: quick
    label: "Left Flipper Switch"
    tags: left_upper_flipper
  s_flipper_left_upper_eos:
    number: playfield_board_lower-10
    label: "Upper Left Flipper EOS"
    type: NC
  s_flipper_right:
    number: cabinet_board-12
    debounce: quick
    label: "Right Flipper Switch"
    tags: right_flipper
  s_flipper_right_eos:
    number:  playfield_board_lower-9
    label: "Right Flipper EOS"
    type: NC

  # Trough Switches & Shooter Lane
  s_trough_1:
    number: playfield_board_lower-0
    label: "Through 1 Switch"
    type: NC
  s_trough_2:
    number: playfield_board_lower-1
    label: "Through 2 Switch"
    type: NC
  s_trough_3:
    number: playfield_board_lower-2
    label: "Through 3 Switch"
    type: NC
  s_trough_4:
    number: playfield_board_lower-3
    label: "Through 4 Switch"
    type: NC
  s_trough_5:
    number: playfield_board_lower-4
    label: "Through 5 Switch"
    type: NC
  s_trough_6:
    number: playfield_board_lower-5
    label: "Through 6 Switch"
    type: NC
  s_jam:
    number: playfield_board_lower-6
    label: "Jam Through Switch"
    type: NC
  s_shooter_lane:
    number: playfield_board_lower-7
    label: "Shooter Lane Switch"
    tags: shooter_lane

#Bumpers and slings
  s_bumper_left:
    number: playfield_board_upper-9
    platform_settings:         # faster response, but still dampens chatter
      debounce_open: 3ms
      debounce_close: 20ms
    label: "Left Pop Spoon"
    tags: [pop bumper, playfield]
  s_bumper_center:
    number: playfield_board_upper-10
    platform_settings:         # faster response, but still dampens chatter
      debounce_open: 3ms
      debounce_close: 20ms
    label: "Center Pop Spoon"
    tags: [pop bumper, playfield]
  s_bumper_right:
    number: playfield_board_upper-8
    platform_settings:         # faster response, but still dampens chatter
      debounce_open: 3ms
      debounce_close: 20ms
    label: "Right Pop Spoon"
    tags: [pop bumper, playfield]
  s_slingshot_left:
    number:  playfield_board_lower-16
    platform_settings:         # faster response, but still dampens chatter
      debounce_open: 3ms
      debounce_close: 20ms
    label: "Left Sling Switch"
    tags: [slingshot, playfield]
  s_slingshot_right:
    number: playfield_board_lower-17
    platform_settings:         # faster response, but still dampens chatter
      debounce_open: 3ms
      debounce_close: 20ms
    label: "Right Sling Switch"
    tags: [slingshot, playfield]

# Inlanes
  s_outlane_left:
    number: playfield_board_lower-11
    label: "Left Outlane Switch"
    tags: [playfield, playfield_active]
  s_inlane_left:
    number: playfield_board_lower-12
    label: "Left Inlane Switch"
    tags: [playfield, playfield_active]
  s_inner_inlane_right:
    number: playfield_board_lower-13
    label: "Right Inner Inlane Switch"
    tags: [playfield, playfield_active]
  s_outer_inlane_right:
    number: playfield_board_lower-14
    label: "Right Outer Inlane Switch"
    tags: [playfield, playfield_active]
  s_outlane_right:
    number: playfield_board_lower-15
    label: "Right Outlane Switch"
    tags: [playfield, playfield_active]
  s_mig_lane_left:
    number: playfield_board_upper-12
    label: "Mig Left Switch"
    tags: [playfield, playfield_active]
  s_mig_lane_right:
    number: playfield_board_upper-13
    label: "Mig Right Switch"
    tags: [playfield, playfield_active]

# Orbits and main shots
  s_lane_left:
    number:  playfield_board_upper-7
    label: "Left Lane Switch"
    tags: [playfield, playfield_active]
  s_orbit_left:
    number: playfield_board_upper-11
    label: "Left Orbit Switch"
    tags: [playfield]
  s_orbit_upper:
    number: playfield_board_upper-26
    label: "Upper Orbit Switch"
    tags: [playfield, playfield_active]
  s_orbit_lower:
    number: playfield_board_upper-25
    label: "Lower Orbit Switch"
    tags: [playfield, playfield_active]
  s_orbit_right:
    number: playfield_board_upper-27
    label: "Right Orbit Switch"
    tags: [playfield]
  s_lane_right:
    number: playfield_board_lower-18
    label: "Right Lane Switch"
    tags: [playfield]

# Target & Stand Up's
  s_i_iceman_target:
    number: playfield_board_lower-25
    label: "Iceman I Switch"
    tags: [standup target, playfield, playfield_active]
  s_c_iceman_target:
    number: playfield_board_lower-26
    label: "Iceman C Switch"
    tags: [standup target, playfield, playfield_active]
  s_e_iceman_target:
    number: playfield_board_lower-27
    label: "Iceman E Switch"
    tags: [standup target, playfield, playfield_active]
  s_m_iceman_target:
    number: playfield_board_lower-30
    label: "Iceman M Switch"
    tags: [standup target, playfield, playfield_active]
  s_a_iceman_target:
    number: playfield_board_lower-28
    label: "Iceman A Switch"
    tags: [standup target, playfield, playfield_active]
  s_n_iceman_target:
    number: playfield_board_lower-29
    label: "Iceman N Switch"
    tags: [standup target, playfield, playfield_active]
  s_l_lock_target:
    number: playfield_board_upper-0
    label: "Locl k Switch"
    tags: [standup target, playfield, playfield_active]
  s_o_lock_target:
    number: playfield_board_upper-1
    label: "Lock O Switch"
    tags: [standup target, playfield, playfield_active]
  s_c_lock_target:
    number: playfield_board_upper-2
    label: "Lock C Switch"
    tags: [standup target, playfield, playfield_active]
  s_k_lock_target:
    number: playfield_board_upper-3
    label: "Lock K Switch"   
    tags: [standup target, playfield, playfield_active]
  s_barrier_target:
    number: playfield_board_upper-5
    label: "Barrier Switch"
    tags: [standup target, playfield, playfield_active]
  s_flight_gear_target:
    number: playfield_board_upper-4
    label: "Flight Gear Switch"
    tags: [standup target, playfield, playfield_active]

# Spinner
  s_spinner:
    number: playfield_board_upper-15
    debounce: quick
    label: "Spinner"
    tags: [playfield, playfield_active]

# Ramps and Locks
  s_ramp_left_exit:
    number: playfield_board_upper-16
    label: "Left Ramp Switch"
    tags: [ramp, playfield, playfield_active]
  s_ramp_right_exit:
    number:  playfield_board_upper-21
    label: "Right Ramp Switch"
    tags: [ramp, playfield, playfield_active]
  s_ramp_inner_exit:
    number: playfield_board_upper-22
    label: "Rigth Inner Exit Ramp Switch"
    tags: [ramp, playfield, playfield_active]
  s_ramp_tower_exit:
    number: playfield_board_upper-20
    label: "Tower Ramp Switch"
    tags: [ramp, playfield, playfield_active]
  s_lock_plunger:
    number: playfield_board_upper-19
    label: "Lock Elevator Switch"
    tags: [playfield]
  s_lock_mav:
    number: playfield_board_upper-17
    label: "Mav Lock Switch"
    tags: [playfield, playfield_active]
  s_lock_goose:
    number: playfield_board_upper-18
    label: "Goose Lock Switch"
    tags: [playfield, playfield_active]
  s_mode_start:
    number: playfield_board_upper-6
    label: "Mode Start Switch"
    tags: [playfield]
