#config_version=6
##############################################################################
# TOP GUN SERVICE MODE - SWITCH STATE EVENTS
# This file posts events when switches change state during switch test
# Include in the mode via the mode's config list
##############################################################################

event_player:
  ##############################################
  # SWITCH STATE MONITORING
  # Posts service_switch_activated for any switch hit during switch test
  # Also posts state change events for Godot to update display
  ##############################################
  
  # All switches - post activation event (for sound)
  s_start_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_tilt_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_coin_door_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_coin_door_service_1_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_coin_door_service_2_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_coin_door_service_3_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_coin_door_service_4_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_coin_door_credit_right_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_coin_door_credit_left_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_flipper_left_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_flipper_left_eos_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_flipper_left_upper_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_flipper_left_upper_eos_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_flipper_right_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_flipper_right_eos_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_trough_1_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_trough_2_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_trough_3_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_trough_4_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_trough_5_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_trough_6_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_jam_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_shooter_lane_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_bumper_left_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_bumper_center_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_bumper_right_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_slingshot_left_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_slingshot_right_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_outlane_left_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_inlane_left_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_inner_inlane_right_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_outer_inlane_right_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_outlane_right_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_mig_lane_left_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_mig_lane_right_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_lane_left_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_orbit_left_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_orbit_upper_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_orbit_lower_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_orbit_right_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_lane_right_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_i_iceman_target_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_c_iceman_target_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_e_iceman_target_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_m_iceman_target_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_a_iceman_target_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_n_iceman_target_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_l_lock_target_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_o_lock_target_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_c_lock_target_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_k_lock_target_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_barrier_target_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_flight_gear_target_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_spinner_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_ramp_left_exit_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_ramp_right_exit_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_ramp_inner_exit_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_ramp_tower_exit_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_lock_plunger_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_lock_mav_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_lock_goose_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
  s_mode_start_active{mode.top_gun_service.active and machine.service_menu_level==1}:
    - service_switch_activated
